const stateData = [
  {
    name: "Andhra Pradesh",
    economy: 12.6,
    gdp: 9.9,
    literacyRate: 67.41,
  },
  {
    name: "Maharashtra",
    economy: 29.4,
    gdp: 15.5,
    literacyRate: 82.34,
  },
  {
    name: "Uttar Pradesh",
    economy: 17.9,
    gdp: 6.8,
    literacyRate: 67.68,
  },
  {
    name: "Tamil Nadu",
    economy: 17.1,
    gdp: 12.5,
    literacyRate: 80.09,
  },
  {
    name: "Bihar",
    economy: 3.2,
    gdp: 1.6,
    literacyRate: 61.8,
  },
  {
    name: "West Bengal",
    economy: 11.2,
    gdp: 7.8,
    literacyRate: 76.26,
  },
  {
    name: "Madhya Pradesh",
    economy: 9.6,
    gdp: 3.2,
    literacyRate: 69.32,
  },
  {
    name: "Karnataka",
    economy: 18.1,
    gdp: 11.2,
    literacyRate: 75.6,
  },
  {
    name: "Rajasthan",
    economy: 8.3,
    gdp: 3.5,
    literacyRate: 66.11,
  },
  {
    name: "Gujarat",
    economy: 20.5,
    gdp: 10.3,
    literacyRate: 79.31,
  },
  {
    name: "Orissa",
    economy: 5.4,
    gdp: 2.8,
    literacyRate: 72.87,
  },
  {
    name: "Kerala",
    economy: 6.2,
    gdp: 4.5,
    literacyRate: 94.0,
  },
  {
    name: "Telangana",
    economy: 10.1,
    gdp: 8.3,
    literacyRate: 72.8,
  },
  {
    name: "Assam",
    economy: 4.1,
    gdp: 1.7,
    literacyRate: 72.19,
  },
  {
    name: "Punjab",
    economy: 6.6,
    gdp: 4.1,
    literacyRate: 75.84,
  },
  {
    name: "Haryana",
    economy: 8.6,
    gdp: 5.3,
    literacyRate: 75.55,
  },
  {
    name: "Chhattisgarh",
    economy: 4.5,
    gdp: 1.5,
    literacyRate: 71.04,
  },
  {
    name: "Jharkhand",
    economy: 5.1,
    gdp: 1.6,
    literacyRate: 66.41,
  },
  {
    name: "Uttarakhand",
    economy: 4.2,
    gdp: 1.7,
    literacyRate: 78.82,
  },
  {
    name: "Himachal Pradesh",
    economy: 3.1,
    gdp: 2.1,
    literacyRate: 82.8,
  },
  {
    name: "Tripura",
    economy: 1.3,
    gdp: 0.5,
    literacyRate: 87.22,
  },
  {
    name: "Meghalaya",
    economy: 0.9,
    gdp: 0.4,
    literacyRate: 75.48,
  },
  {
    name: "Manipur",
    economy: 0.6,
    gdp: 0.3,
    literacyRate: 76.94,
  },
  {
    name: "Nagaland",
    economy: 0.5,
    gdp: 0.2,
    literacyRate: 79.55,
  },
  {
    name: "Goa",
    economy: 3.7,
    gdp: 2.9,
    literacyRate: 88.7,
  },
  {
    name: "Arunachal Pradesh",
    economy: 0.6,
    gdp: 0.3,
    literacyRate: 66.95,
  },
  {
    name: "Mizoram",
    economy: 0.3,
    gdp: 0.2,
    literacyRate: 91.33,
  },
  {
    name: "Sikkim",
    economy: 0.8,
    gdp: 0.4,
    literacyRate: 81.42,
  },
  {
    name: "Delhi",
    economy: 12.7,
    gdp: 5.8,
    literacyRate: 86.21,
  },
  {
    name: "Puducherry",
    economy: 0.7,
    gdp: 0.4,
    literacyRate: 85.85,
  },
  {
    name: "Chandigarh",
    economy: 1.2,
    gdp: 0.8,
    literacyRate: 86.77,
  },
  {
    name: "Jammu And Kashmir",
    economy: 4.6,
    gdp: 1.9,
    literacyRate: 77.3,
  },
];

export default stateData;
